org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
codexMobile.versionCode=5
codexMobile.providerRevision=a40fefe7c3a60da14e65fef05106a07e1734afdf
codexMobile.versionName=0.2.0-preview.3
codexMobile.codexVersion=0.144.6
codexMobile.codexArchiveSha256=3539380f431aa72ce1e9ba83cf4d9b2c2a70d12ddf3280bc67c8c59f93bb9eb5
codexMobile.codexBinarySha256=09d6a41d6189b14317ec5d556251e5195e9a4235c28867fc75ee5c1d54be02cd
