org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
codexMobile.versionCode=5
codexMobile.providerRevision=a40fefe7c3a60da14e65fef05106a07e1734afdf
codexMobile.versionName=0.2.0-preview.3
codexMobile.codexVersion=0.145.0
codexMobile.codexArchiveSha256=3a185f6a1e2ec3ce7ebe9ea5ab23a81bfab75470337e66e235b881ca40ac8932
codexMobile.codexBinarySha256=9c5954b50520b68d7d181804965b554f09add95cc8fb0db6a7750111a1296b60
